services:
  db:
    image: postgres:15-alpine
    container_name: user-org-hierarchy-db
    restart: always
    environment:
      POSTGRES_USER: dbUser
      POSTGRES_PASSWORD: dbPassword
      POSTGRES_DB: user_org_hierarchy_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: user-org-hierarchy-api
    restart: always
    ports:
      - '${PORT}:3000'
      - '9464:9464' # metrics
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://dbUser:dbPassword@db:5432/user_org_hierarchy_db # overwrites the .env file for the correct Docker host
    depends_on:
      - db

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - '16686:16686' # UI
      - '4318:4318' # OTLP HTTP (O que o SDK do Node usa)

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ports:
      - '9200:9200'

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - '9090:9090'

volumes:
  postgres_data:
  es_data:
  prometheus_data:
